---
# All ansible-jekyll variables
# Override any in your local ansible group_vars/jekyll.yml
http_user: cloud-user
http_root: /var/www/public
jekyll_version: 3.0.5
ruby_version: 2.3.1

server_hostname: $hostname
git_branch: master
git_user_key: /home/cloud-user/.ssh/docs_deploy_key.pub

# These two will form the path for the git remote:
# e.g. git@example.com:repos/example-repo.git
git_repo: metapod-docs.git
git_repo_dir: repos
