---
# All ansible-jekyll variables
# Override any in your local ansible group_vars/jekyll.yml
http_user: www-data
http_root: /var/www/public
jekyll_version: 3.0.5
ruby_version: 2.3.1

server_hostname: docs.metacloud.com
git_user_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# These two will form the path for the git remote:
# e.g. git@example.com:repos/example-repo.git
git_repo: metapod-docs.git
git_repo_dir: repos
