---
- name: Create http_user
  user: name={{http_user}} group={{http_user}}
- name: Install nginx
  action: apt pkg=nginx state=installed
- name: Create public HTML directory
  file: dest={{http_root}} mode=0775 owner={{http_user}} group={{http_user}} state=directory
- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
  notify:
    - restart nginx
- name: Copy site configuration
  template: src=default dest=/etc/nginx/sites-available/default mode=0644
  notify:
    - restart nginx
- name: Enable default site
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default
  args: 
    state: link
    mode: 0755
  notify:
    - restart nginx